name: CI/CD - Tests et Couverture

on:
  push:
  pull_request:
jobs:
  backend-tests:
    name: Tests Back-end Spring Boot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Setup JAVA 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      # Mise en cache des packages Maven
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Lance du build, des tests et gébération du rapport de couverture
      - name: Build, Run Tests & Generate Coverage Report
        run: mvn -B clean verify

      # Création d'un artefact github pour enregistrer le rapport
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

  frontend-tests:
    name: Tests Front-End Angular
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Setup Node 18
      - name: Set up Node 18
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      # Installation des dépendances
      - name: Install Dependencies
        run: npm ci

      # Lancement du build
      - name: Build
        run: npm run build

      # Lancement des tests et génération du rapport de couverture
      - name: Run Tests with Coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      # Création d'un artefact github pour enregistrer le rapport
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: frontend-coverage-report
          path: front/coverage/

  sonar-analys:
    name: Analyse SonarQube
    runs-on: ubuntu-latest
    needs:
      - backend-tests
      - frontend-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Mise en cache des packages Sonar et Maven pour accélérer l'analyse
      - name: Cache Sonar packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Mise en cache des packages Maven pour accélérer l'analyse
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Récupération des artefacts
      - name: Download JaCoCo Report
        uses: actions/download-artifact@v7
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

      - name: Download Frontend Coverage
        uses: actions/download-artifact@v7
        with:
          name: frontend-coverage-report
          path: front/coverage/

      # Setup JAVA 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      # Lancement de l'analyse SonarQube
      - name: Run Sonar Analysis
        run: |
          cd back
          mvn -B sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
